@baseUrl = "http://localhost:3000/api"

#Categories
#@name getAllCategories
get {{baseUrl}}/categories

###

# @name addNewCategpries
POST {{baseUrl}}/categories
Content-Type: application/json

{
    "name":"alo"
}

# @name addNewUpdateCategpries
PATCH  {{baseUrl}}/categories/2
Content-Type: application/json

{
    "name":"alo"
}

###
# @name removeCategories
POST {{baseUrl}}/categories/2
